return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.8.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 15,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 15,
  nextobjectid = 139,
  properties = {},
  tilesets = {
    {
      name = "spritesheet",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "../textures/world/spritesheet.png",
      imagewidth = 1024,
      imageheight = 1024,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 1024,
      tiles = {
        {
          id = 940,
          objectGroup = {
            type = "objectgroup",
            draworder = "index",
            id = 2,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "rectangle",
                x = 8,
                y = 14,
                width = 24,
                height = 18,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        },
        {
          id = 941,
          objectGroup = {
            type = "objectgroup",
            draworder = "index",
            id = 2,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 14,
                width = 24,
                height = 18,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        },
        {
          id = 972,
          objectGroup = {
            type = "objectgroup",
            draworder = "index",
            id = 2,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "rectangle",
                x = 9,
                y = 0,
                width = 23,
                height = 32,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        },
        {
          id = 973,
          objectGroup = {
            type = "objectgroup",
            draworder = "index",
            id = 2,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 23,
                height = 32,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        },
        {
          id = 1004,
          objectGroup = {
            type = "objectgroup",
            draworder = "index",
            id = 2,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "rectangle",
                x = 9,
                y = 0,
                width = 23,
                height = 32,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        },
        {
          id = 1005,
          objectGroup = {
            type = "objectgroup",
            draworder = "index",
            id = 2,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            parallaxx = 1,
            parallaxy = 1,
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 23,
                height = 32,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        }
      }
    }
  },
  layers = {
    {
      type = "group",
      id = 2,
      name = "sprites",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 16,
          height = 15,
          id = 1,
          name = "ground",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34,
            1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
            33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34,
            1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
            33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34,
            1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
            33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34,
            1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
            33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34,
            1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
            33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34,
            1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
            33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34,
            1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
            33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34, 33, 34
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 16,
          height = 15,
          id = 3,
          name = "wall",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            642, 642, 642, 642, 642, 642, 642, 642, 642, 642, 642, 642, 642, 642, 642, 649,
            0, 0, 0, 0, 0, 0, 837, 772, 775, 838, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 837, 772, 775, 838, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 775, 838, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 837, 772, 775, 838, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 837, 772, 775, 642, 642, 651, 652, 642, 642, 642,
            0, 0, 0, 0, 0, 0, 837, 772, 775, 674, 674, 683, 684, 674, 674, 674,
            0, 0, 0, 0, 0, 0, 837, 772, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 840, 774, 646, 642, 642, 651, 652, 642, 642, 642,
            0, 0, 0, 0, 0, 0, 840, 774, 646, 674, 674, 683, 684, 674, 674, 674,
            0, 0, 0, 0, 0, 0, 840, 774, 646, 836, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 840, 774, 646, 836, 0, 0, 0, 0, 0, 0,
            774, 0, 0, 0, 0, 0, 837, 774, 773, 838, 0, 0, 0, 0, 0, 775,
            642, 642, 642, 642, 642, 642, 642, 649, 650, 642, 642, 642, 642, 642, 642, 642,
            706, 706, 706, 706, 706, 706, 706, 681, 682, 706, 706, 706, 706, 706, 706, 706
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 16,
          height = 15,
          id = 5,
          name = "wall2",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            645, 0, 0, 0, 0, 0, 0, 645, 646, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            645, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 16,
          height = 15,
          id = 7,
          name = "nonInflammableFurnitures",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 0, 0, 0, 0, 408, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 440, 1015, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 16,
          height = 15,
          id = 6,
          name = "stairs",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 953, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 986, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 1018, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
          }
        }
      }
    },
    {
      type = "group",
      id = 9,
      name = "flammableStuff",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 11,
          name = "ground",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 84,
              name = "wood",
              type = "",
              shape = "rectangle",
              x = 8.08696,
              y = 32.0435,
              width = 23.8696,
              height = 63.913,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 85,
              name = "wood",
              type = "",
              shape = "rectangle",
              x = 64.0313,
              y = 32.0156,
              width = 63.9688,
              height = 41.9622,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 86,
              name = "wood",
              type = "",
              shape = "rectangle",
              x = 192.016,
              y = 32.1818,
              width = 24.0753,
              height = 41.8182,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 87,
              name = "wood",
              type = "",
              shape = "rectangle",
              x = 64,
              y = 74,
              width = 152,
              height = 198,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 88,
              name = "wood",
              type = "",
              shape = "rectangle",
              x = 8.08889,
              y = 96,
              width = 64,
              height = 320,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 89,
              name = "wood",
              type = "",
              shape = "rectangle",
              x = 165.818,
              y = 272.091,
              width = 50.2727,
              height = 144.091,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 90,
              name = "wood",
              type = "",
              shape = "rectangle",
              x = 72.3636,
              y = 353.273,
              width = 93.6364,
              height = 63.2727,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 91,
              name = "wood",
              type = "",
              shape = "rectangle",
              x = 72.1818,
              y = 272,
              width = 16.5455,
              height = 80.9091,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 10,
          name = "furnitures",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 17,
              name = "chair",
              type = "",
              shape = "rectangle",
              x = 138.875,
              y = 341,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 946,
              visible = true,
              properties = {}
            },
            {
              id = 18,
              name = "chair",
              type = "",
              shape = "rectangle",
              x = 138.25,
              y = 310,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 946,
              visible = true,
              properties = {}
            },
            {
              id = 19,
              name = "chair",
              type = "",
              shape = "rectangle",
              x = 85.5,
              y = 310,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 945,
              visible = true,
              properties = {}
            },
            {
              id = 20,
              name = "chair",
              type = "",
              shape = "rectangle",
              x = 84.25,
              y = 341,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 945,
              visible = true,
              properties = {}
            },
            {
              id = 5,
              name = "table",
              type = "",
              shape = "rectangle",
              x = 128,
              y = 320,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 976,
              visible = true,
              properties = {}
            },
            {
              id = 6,
              name = "table",
              type = "",
              shape = "rectangle",
              x = 96,
              y = 320,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 975,
              visible = true,
              properties = {}
            },
            {
              id = 8,
              name = "table",
              type = "",
              shape = "rectangle",
              x = 128,
              y = 288,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 944,
              visible = true,
              properties = {}
            },
            {
              id = 9,
              name = "table",
              type = "",
              shape = "rectangle",
              x = 96,
              y = 288,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 943,
              visible = true,
              properties = {}
            },
            {
              id = 10,
              name = "table",
              type = "",
              shape = "rectangle",
              x = 128,
              y = 352,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1008,
              visible = true,
              properties = {}
            },
            {
              id = 11,
              name = "table",
              type = "",
              shape = "rectangle",
              x = 96,
              y = 352,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1007,
              visible = true,
              properties = {}
            },
            {
              id = 33,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 448,
              y = 320,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 942,
              visible = true,
              properties = {}
            },
            {
              id = 34,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 416,
              y = 320,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 941,
              visible = true,
              properties = {}
            },
            {
              id = 35,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 416,
              y = 352,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 973,
              visible = true,
              properties = {}
            },
            {
              id = 36,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 416,
              y = 384,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1005,
              visible = true,
              properties = {}
            },
            {
              id = 37,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 448,
              y = 384,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1006,
              visible = true,
              properties = {}
            },
            {
              id = 38,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 448,
              y = 352,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 974,
              visible = true,
              properties = {}
            },
            {
              id = 42,
              name = "chair",
              type = "",
              shape = "rectangle",
              x = 472,
              y = 315,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 932,
              visible = true,
              properties = {}
            },
            {
              id = 43,
              name = "chair",
              type = "",
              shape = "rectangle",
              x = 472,
              y = 347,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 964,
              visible = true,
              properties = {}
            },
            {
              id = 52,
              name = "lamp",
              type = "",
              shape = "rectangle",
              x = 472,
              y = 415,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1001,
              visible = true,
              properties = {
                ["light"] = true
              }
            },
            {
              id = 54,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 352,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 208,
              visible = true,
              properties = {}
            },
            {
              id = 55,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 320,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 176,
              visible = true,
              properties = {}
            },
            {
              id = 56,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 288,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 144,
              visible = true,
              properties = {}
            },
            {
              id = 57,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 320,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 372,
              visible = true,
              properties = {}
            },
            {
              id = 58,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 352,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 404,
              visible = true,
              properties = {}
            },
            {
              id = 60,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 288,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 340,
              visible = true,
              properties = {}
            },
            {
              id = 61,
              name = "carpet",
              type = "",
              shape = "rectangle",
              x = 394.333,
              y = 353.333,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 247,
              visible = true,
              properties = {}
            },
            {
              id = 62,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 448,
              y = 32,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 940,
              visible = true,
              properties = {}
            },
            {
              id = 63,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 416,
              y = 32,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 939,
              visible = true,
              properties = {}
            },
            {
              id = 64,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 416,
              y = 64,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 971,
              visible = true,
              properties = {}
            },
            {
              id = 65,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 448,
              y = 64,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 972,
              visible = true,
              properties = {}
            },
            {
              id = 66,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 416,
              y = 96,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1003,
              visible = true,
              properties = {}
            },
            {
              id = 68,
              name = "bed",
              type = "",
              shape = "rectangle",
              x = 448,
              y = 96,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1004,
              visible = true,
              properties = {}
            },
            {
              id = 69,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 128,
              y = 32,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 242,
              visible = true,
              properties = {}
            },
            {
              id = 70,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 128,
              y = 64,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 274,
              visible = true,
              properties = {}
            },
            {
              id = 71,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 128,
              y = 96,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 306,
              visible = true,
              properties = {}
            },
            {
              id = 72,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 160,
              y = 32,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 243,
              visible = true,
              properties = {}
            },
            {
              id = 73,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 160,
              y = 64,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 275,
              visible = true,
              properties = {}
            },
            {
              id = 74,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 160,
              y = 96,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 307,
              visible = true,
              properties = {}
            },
            {
              id = 75,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 32,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 366,
              visible = true,
              properties = {}
            },
            {
              id = 78,
              name = "placard",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 64,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 430,
              visible = true,
              properties = {}
            },
            {
              id = 81,
              name = "lamp",
              type = "",
              shape = "rectangle",
              x = 384,
              y = 96,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1001,
              visible = true,
              properties = {
                ["light"] = true
              }
            },
            {
              id = 82,
              name = "lamp",
              type = "",
              shape = "rectangle",
              x = 241,
              y = 96.5,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1001,
              visible = true,
              properties = {
                ["light"] = true
              }
            },
            {
              id = 83,
              name = "lamp",
              type = "",
              shape = "rectangle",
              x = 112.25,
              y = 320,
              width = 32,
              height = 32,
              rotation = 0,
              gid = 1001,
              visible = true,
              properties = {
                ["lamp"] = false
              }
            }
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "spawnPoints",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 254,
          y = 404,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
